import React, { createContext, useContext, useState } from "react";

const LanguageContext = createContext();

export const translations = {
  en: {
    // NAVBAR
    products: "Products",
    home: "Home",
    cart: "Cart",
    admin: "Admin",
    login: "Login",
    logout: "Logout",
    register: "Register",
    myOrders: "My Orders",
    profile: "Profile",
    wishlist: "Wishlist",

    // PRODUCTS PAGE
    search: "Search products...",
    showing: "Showing",
    product: "product",
    products_plural: "products",
    addToCart: "Add to Cart",
    added: "Added",
    loading: "Loading Collection",
    noProducts: "No products found",
    collection: "SmartCart Collection",
    ourPremium: "Our",
    premium: "Premium",
    productsTitle: "Products",
    viewDetails: "View Details",
    backToProducts: "Back to Products",
    inStock: "In Stock",
    outOfStock: "Out of Stock",
    category: "Category",
    description: "Description",
    price: "Price",
    quantity: "Quantity",

    // HOME PAGE
    heroEyebrow: "Est. 2024 — SmartCart",
    heroTitle1: "Shop",
    heroTitleEm: "Beyond",
    heroTitle2: "Ordinary",
    heroSub: "Where luxury meets convenience",
    exploreCollection: "Explore Collection",
    joinNow: "Join Now",
    whyChooseUs: "Why Choose Us",
    smartcartDiff: "The",
    smartcartDiffEm: "SmartCart",
    smartcartDiff2: "Difference",
    shopNow: "Shop Now",
    createAccount: "Create Account",
    readyToElevate: "Ready to",
    readyToElevateEm: "Elevate",
    readyToElevate2: "Your Shopping?",
    readyToElevateSub: "Join thousands of discerning customers who trust SmartCart",
    premiumProducts: "Premium Products",
    happyCustomers: "Happy Customers",
    ordersFulfilled: "Orders Fulfilled",
    features: [
      { title: "Curated Selection", desc: "Every product handpicked for quality, craftsmanship, and lasting value." },
      { title: "Secure Checkout",   desc: "Bank-grade encryption protects every transaction you make with us." },
      { title: "Swift Delivery",    desc: "Express shipping ensures your orders arrive pristine and on time." },
      { title: "Dedicated Support", desc: "Our concierge team is available around the clock for your needs." },
    ],
    marqueeItems: ["Free Shipping","Premium Quality","Secure Payment","24/7 Support","Exclusive Collection","Luxury Experience"],
    footerCopy: "© 2024 SmartCart. All rights reserved.",

    // CART PAGE
    yourSelection: "Your Selection",
    shoppingCart: "Shopping Cart",
    cartEmpty: "Your cart is empty",
    cartEmptySub: "Discover our curated collection of premium products",
    exploreCollection2: "Explore Collection →",
    orderSummary: "Order Summary",
    total: "Total",
    proceedCheckout: "Proceed to Checkout",
    continueShopping: "← Continue Shopping",
    processing: "Processing...",
    checkoutFailed: "Checkout failed. Please try again.",
    orderConfirmed: "Order",
    orderConfirmedEm: "Confirmed",
    orderConfirmedSub: "Thank you for your purchase. Your order has been placed and will be processed shortly.",
    continueShoppingBtn: "Continue Shopping →",
    each: "each",
    items: "items",
    item: "item",
    selected: "selected",

    // PAYMENT
    paymentMethod: "Payment",
    payWithCash: "Cash on Delivery",
    payWithCashSub: "Pay when your product arrives at your door",
    payWithCard: "Credit / Debit Card",
    payWithCardSub: "Visa · Mastercard · American Express",
    payWithPaypal: "PayPal",
    payWithPaypalSub: "Pay quickly and securely with your PayPal account",
    sslSecured: "Secured with SSL 256-bit encryption",
    confirmOrder: "Confirm Order",
    free: "Free",
    recommended: "Recommended",

    // REGISTER PAGE
    smartcartMembership: "SmartCart Membership",
    joinTheElite: "Join the",
    joinTheEliteEm: "Elite",
    joinSub: "Create your account and discover a world of premium shopping",
    fullName: "Full Name",
    emailAddress: "Email Address",
    password: "Password",
    fullNamePlaceholder: "Your full name",
    emailPlaceholder: "your@email.com",
    passwordPlaceholder: "Min. 6 characters",
    creatingAccount: "Creating Account...",
    createAccountBtn: "Create Account →",
    alreadyMember: "Already a member?",
    signIn: "Sign in",
    accountCreated: "✓ Account created! Redirecting to login...",
    fillAllFields: "Please fill all fields!",
    registerFailed: "Registration failed!",

    // ADMIN DASHBOARD
    smartcartAdmin: "SmartCart Admin",
    adminDashboard: "Admin Dashboard",
    welcomeAdmin: "Welcome,",
    role: "Role",
    users: "Users",
    productsLabel: "Products",
    orders: "Orders",
    revenue: "Revenue",
    overview: "Overview",
    ordersByStatus: "Orders by Status",
    status: "Status",
    count: "Count",
    noOrders: "No orders yet.",
    top5: "Top 5 Products",
    productLabel: "Product",
    totalSold: "Total Sold",
    noData: "No data yet.",
    manageUsers: "Manage Users",
    id: "ID",
    name: "Name",
    email: "Email",
    roleLabel: "Role",
    actions: "Actions",
    delete: "Delete",
    manageProducts: "Manage Products",
    addProduct: "Add Product",
    stockLabel: "Stock",
    categoryLabel: "Category",
    edit: "Edit",
    editProduct: "✏️ Edit Product",
    addNewProduct: "➕ Add New Product",
    nameLabel: "Name",
    priceLabel: "Price (€)",
    descriptionLabel: "Description",
    save: "Save",
    cancel: "Cancel",
    required: "required",
    loadingData: "Loading data...",
    dataLoaded: "✅ Data loaded!",
    errorLoading: "❌ Error loading data!",
    userDeleted: "✅ User deleted!",
    errorDeleting: "❌ Error deleting!",
    productUpdated: "✅ Product updated!",
    productAdded: "✅ Product added!",
    errorSaving: "❌ Error saving!",
    productDeleted: "✅ Product deleted!",
    confirmDelete: "Are you sure?",

    // MY ORDERS PAGE
    myOrdersTitle: "My",
    myOrdersEm: "Orders",
    noOrdersYet: "No orders yet",
    noOrdersSub: "Explore our premium collection and place your first order",
    exploreProducts: "Explore Products →",
    ordersTotal: "orders total",
    orderNumber: "Order",
    orderDate: "Date",
    orderTotal: "Total",
    cancelOrder: "✕ Cancel",
    cancellingOrder: "Cancelling...",
    confirmCancel: "Are you sure you want to cancel this order?",
    cancelError: "Error cancelling order!",
    orderCancelled: "❌ This order has been cancelled",
    orderDelivered: "✅ Order was delivered successfully",
    arrivalCountdown: "Arrives within",
    orderPlaced: "Order placed",
    estimatedArrival: "Estimated arrival",
    orderArrived: "Order Arrived!",
    orderArrivedSub: "Delivery completed within 24 hours",
    statusPending: "⏳ Pending",
    statusProcessing: "⚙️ Processing",
    statusShipped: "🚚 Shipped",
    statusDelivered: "✅ Delivered",
    statusCancelled: "❌ Cancelled",
    productId: "Product #",
    quantity2: "Quantity",
    noItemDetails: "No item details",
    // ✅ Exchange / Return keys
    exchangeRequest: "Exchange",
    returnRequest: "Return / Defect",
    exchangeSent: "⇄ Exchange request sent to admin. Awaiting confirmation.",
    returnSent: "↩ Defect report sent to admin. Awaiting review.",
    requestSent: "✅ Request sent to admin successfully!",
    requestError: "An error occurred. Please try again.",

    // PROFILE PAGE
    profileTitle: "My Profile",
    profileEyebrow: "My Profile",
    personalInfo: "Personal Information",
    fullNameLabel: "Full Name",
    emailLabel: "Email",
    roleReadonly: "Role",
    memberSince: "Member Since",
    saveChanges: "Save Changes",
    saving: "Saving...",
    dangerZone: "⚠️ Danger Zone",
    dangerZoneDesc: "Deleting your account is irreversible. All data will be lost.",
    deleteAccount: "Delete Account",
    security: "Security",
    changePassword: "Change Password",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmPassword: "Confirm New Password",
    passwordStrength: "Password Strength",
    tooShort: "Too short",
    medium: "Medium",
    strong: "Strong",
    changePasswordBtn: "Change Password",
    changing: "Changing...",
    orderHistory: "Order History",
    noOrdersProfile: "You have no orders yet",
    profileUpdated: "✅ Profile updated!",
    passwordChanged: "✅ Password changed!",
    tabProfile: "👤 My Info",
    tabSecurity: "🔒 Security",
    tabOrders: "📦 History",

    // WISHLIST PAGE
    wishlistTitle: "Wishlist",
    wishlistEyebrow: "My Wishlist",
    wishlistEmpty: "Your wishlist is empty",
    wishlistEmptySub: "Add products to your wishlist by clicking the ♡ icon on the products page.",
    wishlistAddAll: "🛒 Add All to Cart",
    wishlistClear: "Clear List",
    wishlistAddedToCart: "added to cart!",
    wishlistRemoved: "Product removed from wishlist.",
    wishlistAdded: "added to wishlist ♡",
    wishlistSaved: "saved",
    addToCartBtn: "+ Cart",
    viewProduct: "View →",
  },

  al: {
    // NAVBAR
    products: "Produktet",
    home: "Kryefaqja",
    cart: "Shporta",
    admin: "Admin",
    login: "Hyrje",
    logout: "Dalje",
    register: "Regjistrohu",
    myOrders: "Porositë Mia",
    profile: "Profili",
    wishlist: "Lista e Dëshirave",

    // PRODUCTS PAGE
    search: "Kërko produkte...",
    showing: "Duke shfaqur",
    product: "produkt",
    products_plural: "produkte",
    addToCart: "Shto në Shportë",
    added: "Shtuar",
    loading: "Duke ngarkuar",
    noProducts: "Nuk u gjetën produkte",
    collection: "Koleksioni SmartCart",
    ourPremium: "Produktet",
    premium: "Tona",
    productsTitle: "Premium",
    viewDetails: "Shiko Detajet",
    backToProducts: "Kthehu te Produktet",
    inStock: "Në Stok",
    outOfStock: "Jashtë Stoku",
    category: "Kategoria",
    description: "Përshkrimi",
    price: "Çmimi",
    quantity: "Sasia",

    // HOME PAGE
    heroEyebrow: "Est. 2024 — SmartCart",
    heroTitle1: "Bli",
    heroTitleEm: "Përtej",
    heroTitle2: "Zakonshmes",
    heroSub: "Ku luksi takon komoditetin",
    exploreCollection: "Eksploro Koleksionin",
    joinNow: "Bashkohu Tani",
    whyChooseUs: "Pse të Zgjidhni Ne",
    smartcartDiff: "Dallimi i",
    smartcartDiffEm: "SmartCart",
    smartcartDiff2: "",
    shopNow: "Bli Tani",
    createAccount: "Krijo Llogari",
    readyToElevate: "Gati të",
    readyToElevateEm: "Ngritësh",
    readyToElevate2: "Blerjen Tuaj?",
    readyToElevateSub: "Bashkohuni me mijëra klientë që besojnë SmartCart",
    premiumProducts: "Produkte Premium",
    happyCustomers: "Klientë të Kënaqur",
    ordersFulfilled: "Porosi të Përfunduara",
    features: [
      { title: "Seleksion i Kuruar",    desc: "Çdo produkt i zgjedhur me kujdes për cilësi dhe vlerë të qëndrueshme." },
      { title: "Blerje e Sigurt",       desc: "Enkriptimi bankar mbron çdo transaksion që bëni me ne." },
      { title: "Dërgim i Shpejtë",      desc: "Shërbimi ekspres siguron që porositë tuaja të arrijnë në kohë." },
      { title: "Mbështetje e Dedikuar", desc: "Ekipi ynë është i disponueshëm gjatë gjithë kohës për nevojat tuaja." },
    ],
    marqueeItems: ["Dërgim Falas","Cilësi Premium","Pagesë e Sigurt","Mbështetje 24/7","Koleksion Ekskluziv","Eksperiencë Luksi"],
    footerCopy: "© 2024 SmartCart. Të gjitha të drejtat e rezervuara.",

    // CART PAGE
    yourSelection: "Zgjedhja Juaj",
    shoppingCart: "Shporta",
    cartEmpty: "Shporta juaj është bosh",
    cartEmptySub: "Zbuloni koleksionin tonë të produkteve premium",
    exploreCollection2: "Eksploro Koleksionin →",
    orderSummary: "Përmbledhja e Porosisë",
    total: "Totali",
    proceedCheckout: "Vazhdo me Blerjen",
    continueShopping: "← Vazhdo Blerjet",
    processing: "Duke procesuar...",
    checkoutFailed: "Blerja dështoi. Provo përsëri.",
    orderConfirmed: "Porosia",
    orderConfirmedEm: "Konfirmuar",
    orderConfirmedSub: "Faleminderit për blerjen. Porosia juaj është pranuar dhe do të procesohet së shpejti.",
    continueShoppingBtn: "Vazhdo Blerjet →",
    each: "secili",
    items: "artikuj",
    item: "artikull",
    selected: "të zgjedhur",

    // PAYMENT
    paymentMethod: "Pagesa",
    payWithCash: "Pagesë me Kesh",
    payWithCashSub: "Paguaj kur produkti të mbërrijnë te dera jote",
    payWithCard: "Kartë Krediti / Debiti",
    payWithCardSub: "Visa · Mastercard · American Express",
    payWithPaypal: "PayPal",
    payWithPaypalSub: "Paguaj shpejt dhe me siguri me llogarinë tënde PayPal",
    sslSecured: "Pagesa e siguruar me enkriptim SSL 256-bit",
    confirmOrder: "Konfirmo Porosinë",
    free: "Falas",
    recommended: "Rekomanduar",

    // REGISTER PAGE
    smartcartMembership: "Anëtarësia SmartCart",
    joinTheElite: "Bashkohu me",
    joinTheEliteEm: "Elitën",
    joinSub: "Krijo llogarinë tënde dhe zbulo një botë të blerjeve premium",
    fullName: "Emri i Plotë",
    emailAddress: "Adresa Email",
    password: "Fjalëkalimi",
    fullNamePlaceholder: "Emri juaj i plotë",
    emailPlaceholder: "email@juaj.com",
    passwordPlaceholder: "Min. 6 karaktere",
    creatingAccount: "Duke krijuar llogarinë...",
    createAccountBtn: "Krijo Llogarinë →",
    alreadyMember: "Tashmë jeni anëtar?",
    signIn: "Hyr",
    accountCreated: "✓ Llogaria u krijua! Duke ridrejtuar...",
    fillAllFields: "Ju lutem plotësoni të gjitha fushat!",
    registerFailed: "Regjistrimi dështoi!",

    // ADMIN DASHBOARD
    smartcartAdmin: "SmartCart Admin",
    adminDashboard: "Paneli i Adminit",
    welcomeAdmin: "Mirë se vini,",
    role: "Roli",
    users: "Përdorues",
    productsLabel: "Produkte",
    orders: "Porosi",
    revenue: "Të Ardhura",
    overview: "Përmbledhje",
    ordersByStatus: "Porositë sipas Statusit",
    status: "Statusi",
    count: "Numri",
    noOrders: "Nuk ka porosi ende.",
    top5: "Top 5 Produktet",
    productLabel: "Produkti",
    totalSold: "Totali i Shitur",
    noData: "Nuk ka të dhëna ende.",
    manageUsers: "Menaxhimi i Përdoruesve",
    id: "ID",
    name: "Emri",
    email: "Email",
    roleLabel: "Roli",
    actions: "Veprime",
    delete: "Fshi",
    manageProducts: "Menaxhimi i Produkteve",
    addProduct: "Shto Produkt",
    stockLabel: "Stoku",
    categoryLabel: "Kategoria",
    edit: "Ndrysho",
    editProduct: "✏️ Ndrysho Produktin",
    addNewProduct: "➕ Shto Produkt të Ri",
    nameLabel: "Emri",
    priceLabel: "Çmimi (€)",
    descriptionLabel: "Përshkrimi",
    save: "Ruaj",
    cancel: "Anulo",
    required: "i detyrueshëm",
    loadingData: "Duke ngarkuar...",
    dataLoaded: "✅ Të dhënat u ngarkuan!",
    errorLoading: "❌ Gabim gjatë ngarkimit!",
    userDeleted: "✅ Përdoruesi u fshi!",
    errorDeleting: "❌ Gabim gjatë fshirjes!",
    productUpdated: "✅ Produkti u përditësua!",
    productAdded: "✅ Produkti u shtua!",
    errorSaving: "❌ Gabim gjatë ruajtjes!",
    productDeleted: "✅ Produkti u fshi!",
    confirmDelete: "A jeni i sigurt?",

    // MY ORDERS PAGE
    myOrdersTitle: "Porositë",
    myOrdersEm: "Mia",
    noOrdersYet: "Nuk keni porosi ende",
    noOrdersSub: "Eksploroni koleksionin tonë premium dhe bëni porosinë tuaj të parë",
    exploreProducts: "Eksploro Produktet →",
    ordersTotal: "porosi gjithsej",
    orderNumber: "Porosia",
    orderDate: "Data",
    orderTotal: "Totali",
    cancelOrder: "✕ Anulo",
    cancellingOrder: "Duke anuluar...",
    confirmCancel: "A jeni i sigurt që doni ta anuloni këtë porosi?",
    cancelError: "Gabim gjatë anulimit!",
    orderCancelled: "❌ Kjo porosi është anuluar",
    orderDelivered: "✅ Porosia u dorëzua me sukses",
    arrivalCountdown: "Mbërrin brenda",
    orderPlaced: "Porosia u bë",
    estimatedArrival: "Mbërrja e pritshme",
    orderArrived: "Porosia Mbërriti!",
    orderArrivedSub: "Dërgesa u kompletua brenda 24 orëve",
    statusPending: "⏳ Në pritje",
    statusProcessing: "⚙️ Duke u procesuar",
    statusShipped: "🚚 Dërguar",
    statusDelivered: "✅ Dorëzuar",
    statusCancelled: "❌ Anuluar",
    productId: "Produkt #",
    quantity2: "Sasia",
    noItemDetails: "Nuk ka detaje produktesh",
    // ✅ Exchange / Return keys
    exchangeRequest: "Ndërrim",
    returnRequest: "Kthim / Defekt",
    exchangeSent: "⇄ Kërkesa për ndërrim u dërgua te admini. Pret konfirmim.",
    returnSent: "↩ Raporti i defektit u dërgua te admini. Pret shqyrtim.",
    requestSent: "✅ Kërkesa u dërgua te admini me sukses!",
    requestError: "Ndodhi një gabim. Provo përsëri.",

    // PROFILE PAGE
    profileTitle: "Profili Im",
    profileEyebrow: "Profili Im",
    personalInfo: "Informacioni Personal",
    fullNameLabel: "Emri i Plotë",
    emailLabel: "Email",
    roleReadonly: "Roli",
    memberSince: "Anëtar që nga",
    saveChanges: "Ruaj Ndryshimet",
    saving: "Duke ruajtur...",
    dangerZone: "⚠️ Zona e Rrezikshme",
    dangerZoneDesc: "Fshirja e llogarisë është e pakthyeshme. Të gjitha të dhënat do të humbasin.",
    deleteAccount: "Fshi Llogarinë",
    security: "Siguria",
    changePassword: "Ndrysho Fjalëkalimin",
    currentPassword: "Fjalëkalimi Aktual",
    newPassword: "Fjalëkalimi i Ri",
    confirmPassword: "Konfirmo Fjalëkalimin e Ri",
    passwordStrength: "Fuqia e Fjalëkalimit",
    tooShort: "Shumë i shkurtër",
    medium: "I mesëm",
    strong: "I fortë",
    changePasswordBtn: "Ndrysho Fjalëkalimin",
    changing: "Duke ndryshuar...",
    orderHistory: "Historiku i Porosive",
    noOrdersProfile: "Nuk ke ende porosi",
    profileUpdated: "✅ Profili u përditësua!",
    passwordChanged: "✅ Fjalëkalimi u ndryshua!",
    tabProfile: "👤 Të Dhënat",
    tabSecurity: "🔒 Siguria",
    tabOrders: "📦 Historiku",

    // WISHLIST PAGE
    wishlistTitle: "Lista e Dëshirave",
    wishlistEyebrow: "Lista Ime e Dëshirave",
    wishlistEmpty: "Lista jote e dëshirave është bosh",
    wishlistEmptySub: "Shto produkte në wishlist duke klikuar ikonën ♡ në faqen e produkteve.",
    wishlistAddAll: "🛒 Shto Të Gjitha në Shportë",
    wishlistClear: "Pastro Listën",
    wishlistAddedToCart: "u shtua në shportë!",
    wishlistRemoved: "Produkti u hoq nga wishlist.",
    wishlistAdded: "u shtua në wishlist ♡",
    wishlistSaved: "të ruajtura",
    addToCartBtn: "+ Shportë",
    viewProduct: "Shiko →",
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState("en");
  const t = translations[lang];
  const toggleLang = () => setLang(prev => prev === "en" ? "al" : "en");
  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
